hostname: travis-worker-gce-org-prod-2:011c873a-832c-4337-8f7b-33f9ef
version: v1.2.0
instance: testing-gce-f32f9cf5-8b5c-42a4-8fc7-7c5a61e0ae8e:
          travis-ci-python-precise-1448037712

language: ruby
rvm:
  - "2.0.0"

branches:
  only:
    - master

before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - sleep 3

script:
  - bundle exec rake tests:run
